=== rosalynshop/rosalynshop/app/code/Aheadworks/OneStepCheckout/etc/osc_attribute_customization.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="address" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="attribute" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="type" type="addressType" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="attribute">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="metadata" minOccurs="0" maxOccurs="1" />
                <xs:element ref="item" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
            <xs:attribute name="code" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="metadata">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="field" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="metadata" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="index" type="xs:int" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="field">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="editable" type="xs:boolean" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="addressType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="billing"/>
            <xs:enumeration value="shipping"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rosalynshop/rosalynshop/app/code/Aheadworks/OneStepCheckout/etc/adminhtml/osc_attribute_customization.xml
<?xml version="1.0"?>
<!--
/**
* Copyright 2018 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/
-->

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Aheadworks_OneStepCheckout:etc/osc_attribute_customization.xsd">
    <address type="billing">
        <attribute code="firstname">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="lastname">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="street">
            <item index="0">
                <metadata>
                    <field name="required">
                        <editable>false</editable>
                    </field>
                    <field name="visible">
                        <editable>false</editable>
                    </field>
                </metadata>
            </item>
            <item index="1">
                <metadata>
                    <field name="required">
                        <editable>true</editable>
                    </field>
                    <field name="visible">
                        <editable>true</editable>
                    </field>
                </metadata>
            </item>
        </attribute>
        <attribute code="city">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="country_id">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="region">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="region_id">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="postcode">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="telephone">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="company">
            <metadata>
                <field name="required">
                    <editable>true</editable>
                </field>
                <field name="visible">
                    <editable>true</editable>
                </field>
            </metadata>
        </attribute>
    </address>
    <address type="shipping">
        <attribute code="firstname">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="lastname">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="street">
            <item index="0">
                <metadata>
                    <field name="required">
                        <editable>false</editable>
                    </field>
                    <field name="visible">
                        <editable>false</editable>
                    </field>
                </metadata>
            </item>
            <item index="1">
                <metadata>
                    <field name="required">
                        <editable>true</editable>
                    </field>
                    <field name="visible">
                        <editable>true</editable>
                    </field>
                </metadata>
            </item>
        </attribute>
        <attribute code="city">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="country_id">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="region">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="region_id">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="postcode">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="telephone">
            <metadata>
                <field name="required">
                    <editable>false</editable>
                </field>
                <field name="visible">
                    <editable>false</editable>
                </field>
            </metadata>
        </attribute>
        <attribute code="company">
            <metadata>
                <field name="required">
                    <editable>true</editable>
                </field>
                <field name="visible">
                    <editable>true</editable>
                </field>
            </metadata>
        </attribute>
    </address>
</config>
